---
version: '2'
services:
  zookeeper-4:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 9
      ZOOKEEPER_CLIENT_PORT: 52181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:52888:53888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-4:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-4
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_ZOOKEEPER_CONNECT: localhost:52181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:49092
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-5:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-4
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_ZOOKEEPER_CONNECT: localhost:52181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:59092
    extra_hosts:
      - "moby:127.0.0.1"
